---
title: "All SeaTemp Data"
author: "Camila Vargas"
date: "12/3/2021"
output: html_document
---

This scripts puts together all Palmyra Atoll's sea temperature data provided by Allie Hunter (Fish and Wildlife Service)

## Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(janitor)
library(plotly)

## Sets R not to use scientific notations
options(scipen=999) 

data_path <- here::here("8.intermediate_files/")

```


## Read data
```{r}
all_files <- tibble(list.files(data_path, pattern = "sea_temp")) %>% 
  rename(file_name = 1) %>% 
  mutate(path = paste0(data_path, "/", file_name),
         type = "temp",
         year = c(17, 18, 20, 21)) %>% 
  unite(obj_name, type, year, sep = "", remove = FALSE)

for (i in 1:4){
  
  assign(all_files$obj_name[i], read_csv(all_files$path[i]))
}

```

## Adjusting serial num
```{r}
temp17 <- temp17 %>% 
  mutate(serial_num = str_extract(serial_num, "\\d{4}[^\\d]*$") %>% as.numeric(.))
```



## Binding all together

**NOT ALL YEARS HAVE THE SERIAL NUMBER** 
Data form folder 18 and 20 is missing that column

```{r}
temp_complete <-  bind_rows(temp17, temp18, temp20, temp21)
```


## Checking date range

```{r}
## Create a table with date range
date_range <- temp_complete %>% 
  group_by(site_name) %>% 
  summarise(date_begins = min(date),
         date_ends = max(date)) %>% 
  arrange(site_name)

```


Site names
```{r}
sites <- temp_complete %>% 
  select(site_name) %>% 
  distinct() %>% 
  arrange(site_name)
  
  
```

